# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 609552b0e31265419f0936369a200454d824ec039a59003aff6258c1810f9da411e8affcf4bbab19ca2a00f120c9c68f3129344a202b9e285d3ced88d5ec71ef

test:
  secret_key_base: c5c0ceabbf2230f2f51ca5ff68e48b44dd844bf267a056228e84efd457ac5d18d33e6dfb0265f5493748886780bc17b4fd1024354773fc57742b2040c6a528fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
